### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/testez#1]
Hilariously enough, there are no tests written for TestEZ.

This was because there wasn't a good mechanism for writing tests for the system itself and reporting them, but running on an open CI system could make that a bit easier.

**Comment by boynedmaster** [comment]
Sounds like your very own [Lemur](https://github.com/LPGhatguy/Lemur) project would solve this issue when expanded more.

**Comment by LPGhatguy** [comment]
Groundwork for this is laid in https://github.com/Roblox/testez/commit/7b46025c46680ac177a0c90ded4d35c487e6592f

**Comment by LPGhatguy** [comment]
We have a test framework now!
