### ISSUE TITLE
Erroring with an object during a testez test creates an error in error handling

### ISSUE THREAD

**Issue by evaera** [Roblox/testez#122]
TestEZ does not handle error objects (which can now be thrown in addition to strings after a somewhat recent Luau update)

```lua
describe("Test", function()
	itFOCUS("shouldn't error", function()
		error({})
	end)
end)
```

Actual output:

```
21:34:42.814 - TestService: error in error handling
```

Expected output:
```
21:36:29.587 - TestService: ServerScriptService.Lib.init.spec:31: table: 0x6cbcd7d1da7770b1
21:36:29.587 - TestService.TestEZ.TestRunner:80
21:36:29.587 - ServerScriptService.Lib.init.spec:31
21:36:29.588 - TestService.TestEZ.TestRunner:77
21:36:29.588 - TestService.TestEZ.TestRunner:75 function runCallback
21:36:29.588 - TestService.TestEZ.TestRunner:108 function runNode
21:36:29.588 - TestService.TestEZ.TestRunner:143 function runPlanNode
21:36:29.589 - TestService.TestEZ.TestRunner:152 function runPlanNode (x2)
21:36:29.589 - TestService.TestEZ.TestRunner:38 function runPlan
21:36:29.590 - TestService.TestEZ.TestBootstrap:127 function run
21:36:29.590 - TestService.run:1
21:36:29.590 - 
```

Suggested fix: call tostring on error value before passing to `TestService:Error`

**Comment by MagiMaster** [comment]
Digging in to this a bit more, this happens way earlier in the process than what I expected. It's actually causing a problem in `debug.traceback` when the test runner is first collecting the error. Everything else is fine with the error being an object already.

**Comment by Dionysusnu** [comment]
This is still an issue if a search string is passed into `expect(function() error({}) end).to.throw("search")`.
[This line](https://github.com/Roblox/testez/blob/25d957d4d5c4c02a52843ef43e72f21f973c2908/src/Expectation.lua#L272) calls `:find` on the `err` directly, assuming it is a string, even though it is not.
