### ISSUE TITLE
Expectations failing do not provide useful output

### ISSUE THREAD

**Issue by Quenty** [Roblox/testez#15]
```
13:15:56.876 - TestService: Blah.Blah.Test:32: assertion failed!
```

Is the effective output of a failed assertion, where as it should output both what the expected output was, and what the input was, as well as a pragmatically generated condition

**Comment by LPGhatguy** [comment]
If you're using `assert(condition)`, of course there's no useful output, you didn't provide one!

TestEZ's built-in `expect` function _does_ have nicer messages though:

https://github.com/Roblox/testez/blob/master/lib/Expectation.lua#L135-L146

**Comment by Quenty** [comment]
You're right! My assertion was actually in _my_ code, so this is entirely my fault.
