### ISSUE TITLE
negated throw gives the wrong error message

### ISSUE THREAD

**Issue by Kampfkarren** [Roblox/testez#36]
Consider:

```
expect(function()
    error("nope")
end).never.to.throw()
```

This will give the same error as if it were not negated:

`Expected function to throw an error, but it did not.`

**Comment by jeparlefrancais** [comment]
Apparently, the error message is also wrong with a regular throw too

```lua
expect(function() end).to.throw()
```

Gives `Expected function to succeed, but it threw an error: nil`
