### ISSUE TITLE
Error on expect(...) if there's more than one argument

### ISSUE THREAD

**Issue by Kampfkarren** [Roblox/testez#37]
Similar to #34. 

Sometimes, I'll think expect is similar to assert_eq, and write something like:

expect(x, 3)

TestEZ doesn't stop this, and it can be a bit annoying to debug. Even with #34, the error that could give wouldn't be as insightful as an error specific to this situation.

**Comment by LPGhatguy** [comment]
I think we should make all of the functions much much more strict to try to catch errors like this.

This is probably the most annoying one!
