### ISSUE TITLE
Example of async test

### ISSUE THREAD

**Issue by MichaelMcDonnell** [Roblox/testez#50]
I'm trying to write a test that calls a function that simulates network delay (using the Roblox delay function). The test suite finishes before the expect in the callback is called. Is there a way to wait for the callbacks to have been called? I don't see anything about async testing in the documentation?

**Comment by MichaelMcDonnell** [comment]
I just found out that we typically don't use callbacks but use yield function instead for async. I also found out that HACK_NO_XPCALL() must be place in the describe block if you have a wait. Otherwise you'll get the odd error message "attempt to yield across metamethod/C-call boundary".

**Comment by LPGhatguy** [comment]
Due to some other engine changes (`xpcall` now supporting yielding), asynchronous tests should now work out-of-the-box!
