### ISSUE TITLE
Existing tests are erroring from expect() only allowing one argument

### ISSUE THREAD

**Issue by vocksel** [Roblox/testez#52]
2d15296 introduces a requirement for `expect()` to only allow one argument. This breaks tests for at least Promises and Cryo.

For Promises specifically, `string.find` is used for an expectation, but because this function returns a tuple, it causes expect() to throw an error.

https://github.com/LPGhatguy/roblox-lua-promise/blob/master/lib/init.spec.lua#L73

For `Cryo.None`, tests fail because `string.find` is used there as well:

```lua
it("should have a nice string name", function()
	local coerced = tostring(None)

	expect(coerced:find("^userdata: ")).never.to.be.ok()
	expect(coerced:find("None")).to.be.ok()
end)
```

**Comment by LPGhatguy** [comment]
I wonder if it's worth rolling back this change. We could push forward with stricter argument validation across the board and accept the compatibility problems, or we could fall back to the previous behavior and fix this as part of Expectation v2 or a brand new assertion syntax.

**Comment by LPGhatguy** [comment]
We've rolled back this change, see #55.
