### ISSUE TITLE
Fill out self-test coverage

### ISSUE THREAD

**Issue by MagiMaster** [Roblox/testez#75]
The test framework itself needs to be well covered by tests.

**Comment by MagiMaster** [comment]
The coverage of most of the main code is pretty good now. The big gaps left are TestBootstrap.run (which is being considered for replacement anyway) and the reporting parts of the code.

**Comment by LPGhatguy** [comment]
Do you think our coverage is good enough to close this overarching issue?

**Comment by MagiMaster** [comment]
If you'd prefer to break it down in to more specific issues, that'd be fine. I the gaps I mentioned above need to be closed before calling it good though,

**Comment by LPGhatguy** [comment]
I filed a new issue for test reports (auto-linked above), and updated the description of #66 to include TestBootstrap replacement and testing.
