### ISSUE TITLE
Handle multiple it blocks with the same description

### ISSUE THREAD

**Issue by MagiMaster** [Roblox/testez#93]
Right now, the final it block will overwrite the rest. This should either run all tests anyway, or fail the tests. Until we've verified that no current tests do this, we might need to make it a warning though.

**Comment by amoss-roblox** [comment]
I don't think it should run the duplicates anyway as this would be likely to confuse any report consumer (and person running the tests!). I'm supportive of an error or at least a warning.

**Comment by MagiMaster** [comment]
I want to disagree with you in favor of allowing a wider variety of use cases, but really I can't think of a good reason to duplicate it block descriptions. Making this an error is probably the right way to go. Also, I agree that it would confuse the person who had to figure out which of the dozen tests actually failed.
